[package]
name = "fibonacci"
version = "0.1.0"
authors = ["sam.z <45636987@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
